name: linux_py38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - affine=2.3.0=pyhd3eb1b0_0
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h8c45485_0
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.3.29=h06a4308_1
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h578d9bd_2
  - cffi=1.15.0=py38hd667e15_1
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.82.0=h7f8727e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - descartes=1.1.0=py_4
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fiona=1.8.13.post1=py38hc820daa_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - freexl=1.0.6=h27cfd23_0
  - fsspec=2022.2.0=pyhd3eb1b0_0
  - gdal=3.0.2=py38h2c27f0e_2
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=hd69d5b1_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py38h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2019.4=243
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.2.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - json-c=0.13.1=h1bed415_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py38h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.12.0=py38h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kealib=1.4.14=hb50703a_1
  - kiwisolver=1.3.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libboost=1.73.0=h3ff78a5_11
  - libcurl=7.82.0=h0b77cf5_0
  - libdap4=3.19.1=h6ec2957_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgdal=3.0.2=he6cead7_2
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libkml=1.3.0=h7ecb851_5
  - libmklml=2019.0.5=h06a4308_0
  - libnetcdf=4.8.1=h42ceab0_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=hc2c5182_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=4.3.0a=hbedb2dc_20
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libzip=1.5.1=h8d318fa_1003
  - libzopfli=1.0.3=he6710b0_0
  - locket=0.2.1=py38h06a4308_2
  - lz4-c=1.9.3=h295c915_1
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - ninja=1.10.2=py38hd09550d_3
  - notebook=6.4.8=py38h06a4308_0
  - numexpr=2.7.3=py38hb2eb853_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - palettable=3.3.0=py_0
  - pandas=1.4.2=py38h295c915_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=0.81.0=h01f5e8b_2
  - poppler-data=0.4.11=h06a4308_0
  - proj=6.2.1=h05a3930_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py38hb3025e9_1
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysal=2.1.0=py_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.3.0=py38h7f8727e_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - rasterio=1.2.10=py38h9a6c7ee_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - rtree=0.9.7=py38h06a4308_1
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.6.2=py38h91f5cce_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38h06a4308_0
  - shapely=1.7.0=py38h7c4d384_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py38h06a4308_1
  - snuggs=1.4.7=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.2=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tiledb=2.2.9=hffe1d7a_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.12.0=py38_cpu
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xerces-c=3.2.3=h780794e_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - adal==1.2.7
    - appdirs==1.4.4
    - argcomplete==2.0.0
    - azure-common==1.1.28
    - azure-core==1.23.1
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==2.0.0
    - azure-mgmt-containerregistry==9.1.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==20.1.0
    - azure-mgmt-storage==19.1.0
    - azureml-core==1.41.0.post1
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.2
    - contextlib2==21.6.0
    - docker==5.0.3
    - efficientnet-pytorch==0.7.1
    - elevation==1.1.3
    - fasteners==0.17.3
    - geojson==2.5.0
    - humanfriendly==10.0
    - isodate==0.6.1
    - jeepney==0.8.0
    - jmespath==0.10.0
    - jsonpickle==2.1.0
    - knack==0.9.0
    - mercantile==1.2.1
    - msal==1.17.0
    - msal-extensions==0.3.1
    - msrest==0.6.21
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - overpy==0.6
    - paramiko==2.10.4
    - pathspec==0.9.0
    - pkginfo==1.8.2
    - portalocker==2.4.0
    - pyasn1==0.4.8
    - pyjwt==2.3.0
    - pynacl==1.5.0
    - rasterstats==0.16.0
    - requests-oauthlib==1.3.1
    - richdem==0.3.4
    - rioxarray==0.11.1
    - secretstorage==3.3.2
    - simplejson==3.17.6
    - supermercado==0.2.0
    - tabulate==0.8.9
    - urllib3==1.26.7
    - utm==0.7.0
    - xarray==2022.3.0
prefix: /root/anaconda3/envs/linux_py38
